### PR TITLE
Add Create Forum Channel

### PR DESCRIPTION
**Pull request by TheMonDon**
Made a separate PR for this new action

### CODE REVIEW

**Comment by RobertBorghese** [comment]
When setting the "type", could we use the enum version instead of just 15 directly? That's how Create Voice Channel is doing it. Good for porting in the future

**Review by almeidx — COMMENTED** [review]
Missing support for 
- availableTags
- defaultReactionEmoji
- defaultAutoArchiveDuration
- defaultSortOrder
- defaultForumLayout

**Comment by TheMonDon** [comment]
> Missing support for
> 
>     * availableTags
> 
>     * defaultReactionEmoji
> 
>     * defaultAutoArchiveDuration
> 
>     * defaultSortOrder
> 
>     * defaultForumLayout

I can add these if @RobertBorghese would like them, but the action already has quite a bit of stuff inside and a scrollbar, I know he likes to keep the actions more simple.

**Comment by RobertBorghese** [comment]
I'll take care of adding the extra stuff later. 👌

**Pull request merged**
